# Site settings
title: Andrew JS Maguire
phone: 484.824.0897
email: ajm221@pitt.edu
url: https://andrewjsmaguire.github.io
description: "Coming soon..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#333333'

# Footer settings
footer: Andrew JS Maguire

# Build settings
markdown: kramdown
permalink: pretty
